name: 🐳 Build and Deploy Docker

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.github/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions: write-all

jobs:
  build-and-push:
    runs-on: arc-runners-default
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        service:
          - open-insurance-mop-gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: | 
            mvn --batch-mode --update-snapshots verify
            mvn clean package -DskipTests

      #- name: Install Maven
       # run: |
       #   sudo apt update
       #   sudo apt install -y maven

     # - name: Build with Maven
      #  run: mvn clean package -DskipTests

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            # Mantém a tag com o nome da branch (para histórico)
            type=ref,event=branch
            # Gera a tag dinâmica com o SHA curto, usando o nome da branch como prefixo
            type=sha,format=short,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-aks:
    needs: build-and-push
    runs-on: arc-runners-default
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - service: open-insurance-mop-gateway
            deployment: mop-gateway
            namespace: gateway

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: AKS Get Credentials
        run: |
          az aks get-credentials --name azu-aks-mop-client-dev --resource-group azu-rg-mop-client-dev --overwrite-existing

      - name: Set Image on Deployment
        env:
          ALL_SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          SECRET_NAME="${{ matrix.deployment }}"
          cat <<EOF > tmp.env
          JWS_KID=${{ secrets.JWS_KID }}
          JWS_ORG_ID=${{ secrets.JWS_ORG_ID }}
          EXTERNAL_REQUEST_URL=${{ secrets.EXTERNAL_REQUEST_URL }}
          EXTERNAL_API_DATA_ANONYMIZATION=${{ secrets.EXTERNAL_API_DATA_ANONYMIZATION }}
          JWS_PRIVATE_KEY=${{ secrets.JWS_KIJWS_PRIVATE_KEYD }}
          RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_VALIDATOR_HOST=${{ secrets.RABBITMQ_VALIDATOR_HOST }}
          MOP_PAYLOAD_SIGNING_PRIVATE_KEY_PEM=${{ secrets.MOP_PAYLOAD_SIGNING_PRIVATE_KEY_PEM }}
          MOP_PAYLOAD_SIGNING_ENABLED=${{ secrets.MOP_PAYLOAD_SIGNING_ENABLED }}
          RABBITMQ_VALIDATOR_PORT=${{ secrets.RABBITMQ_VALIDATOR_PORT }}
          # Adicione as demais secrets do GitHub aqui...
          EOF

          kubectl create secret generic $SECRET_NAME \
            --from-env-file=tmp.env \
            --namespace=${{ matrix.namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -

          # Injeta a Secret inteira no Deployment (Equivalente ao envFrom)
          kubectl set env deployment/${{ matrix.deployment }} \
            --from=secret/$SECRET_NAME \
            -n ${{ matrix.namespace }}

          # Atualiza a imagem
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAG="${{ github.ref_name }}-$SHORT_SHA"
          IMAGE="ghcr.io/${{ github.repository }}/${{ matrix.service }}:$TAG"
          echo "Atualizando deployment '${{ matrix.deployment }}' com a imagem: $IMAGE"
          kubectl set image deployment/${{ matrix.deployment }} ${{ matrix.deployment }}=$IMAGE -n ${{ matrix.namespace }}
